# Simple comparison of incremental `groupBy()` for CS-B, CS-D and DRL

In this directory:

* First run `mvn clean install` to compile the JMH benchmark.
* Then run `java -jar target/benchmarks.jar` to execute the JMH benchmark.

The benchmark runs in three scenarios:

* "EM-GN" is a pure Drools exec model where groupBy is implemented using a dedicated Phreak node.
* "EM-3R" is a pure Drools exec model where groupBy is implemented using a 3-rule solution.
* "DRL" is a DRL-based rule with accumulate.
* "CS-D" uses a constraint stream with groupBy() and the Drools impl.
* "CS-B" uses the same constraint stream, but switches to Bavet impl.

== V3

Adds two more scenarios, "EM-GN" and "EM-3R".

== V2

This benchmark has two variants:

* "changeComputer" picks a `CloudProcess` at random and updates the `CloudComputer` for another one. Updates 1 fact.
* "swapComputers" picks two `CloudProcess` at random and swaps their `CloudComputer` instances. Updates 2 facts.

In either variant, the initial creation and filling of the session is not measured.

This is the raw JMH result from my laptop (quad-core i7 w/ Fedora 33, OpenJDK 15):

  Benchmark                   (algo)   Mode  Cnt       Score       Error  Units
  MyBenchmark.changeComputer     DRL  thrpt   25  152419,851 ± 16520,207  ops/s
  MyBenchmark.changeComputer    CS-B  thrpt   25  333145,932 ± 28443,935  ops/s
  MyBenchmark.changeComputer    CS-D  thrpt   25   41909,513 ±  7576,061  ops/s
  MyBenchmark.swapComputers      DRL  thrpt   25  132066,952 ± 16783,980  ops/s
  MyBenchmark.swapComputers     CS-B  thrpt   25  262115,845 ± 12672,076  ops/s
  MyBenchmark.swapComputers     CS-D  thrpt   25   39348,012 ±  3376,390  ops/s

== V1 (See Git history)

This benchmark has two variants:

* "incremental" inserts every planning entity individually and evaluates after every insert.
* "allAtOnce" first inserts every planning entity and then evaluates once.

This is the raw JMH result from my laptop (quad-core i7 w/ Fedora 33, OpenJDK 15):

  Benchmark                (algo)   Mode  Cnt    Score    Error  Units
  MyBenchmark.allAtOnce       DRL  thrpt   25  338,101 ± 17,071  ops/s
  MyBenchmark.allAtOnce      CS-B  thrpt   25  844,079 ± 29,981  ops/s
  MyBenchmark.allAtOnce      CS-D  thrpt   25  121,823 ±  6,200  ops/s
  MyBenchmark.incremental     DRL  thrpt   25  154,339 ±  9,140  ops/s
  MyBenchmark.incremental    CS-B  thrpt   25  537,381 ± 23,206  ops/s
  MyBenchmark.incremental    CS-D  thrpt   25   59,895 ±  2,430  ops/s
